### ISSUE TITLE
Will there be any more updates?

### ISSUE THREAD

**Issue by foxayy** [201853910/VMware-vSphere-Hypervisor-ESXi-#1]
Will it be updated again？there's already version 8.0 on the vmware website

**Comment by 201853910** [comment]
我的认证设备丢了，恢复代码也不知道放到哪里了，现在github账号访问权丢了，正在想办法登录账户。
这个回复是我通过邮箱回复的，文字排版可能有点问题

Alex_Yan ***@***.***> 于2023年10月24日周二 09:59写道：
